#!/bin/bash

# Setup RPi

# https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2021-05-28/

# var - start

# Colored text
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
OFF='\033[0m'

# var - stop

# def func - start

# func for printing start of new task in a specific color

# def func - end


# script - start

IAM=$(id -u)
if [ $IAM -gt 0 ]
then
	echo -e "${RED}You must use sudo to run this script.${OFF}"
	echo "sudo $0"
	exit 1
fi

read -p 'Enter the hostname for this RaspberryPi: ' HNAME

read -p 'Enter an static IP address: ' HIP

read -p 'Enter a DNS server address: ' HDNS

read -p 'Enter the router IP: ' ROUTERIP

read -p 'Enter an interface to configure: ' INTERFACE

echo ""

# creat user hunter
useradd -m -p pihunter hunter
usermod -aG adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi hunter
sleep 3
# echo "$YELLOW Enter a password for the new user - hunter - $OFF"
# passwd hunter

# update pi / install required packages

apt update -y
apt install htop tmux vim git prads tcpdump scapy tshark foremost yara '^libssl1.0.[0-9]$' libunwind8 network-manager -y && sudo apt upgrade -y

# Stop unncessessary services
echo "" >> /boot/config.txt
echo "# Disable Bluetooth and WiFi" >> /boot/config.txt
echo "dtoverlay=disable-wifi" >> /boot/config.txt
echo "dtoverlay=disable-bt" >> /boot/config.txt

# Bluetooth
systemctl stop bluetooth.service
systemctl disable bluetooth.service
systemctl stop bluetooth.target
systemctl disable bluetooth.target
# wpasupplicant
systemctl stop wpa_supplicant
systemctl disable wpa_supplicant

# Set Hostname

hostnamectl set-hostname $HNAME
echo ‘127.0.0.1       localhost’ > /etc/hosts
echo ‘::1	     localhost ip6-localhost ip6-loopback’ >> /etc/hosts
echo ‘ff02::1.        ip6-allnodes’ >> /etc/hosts
echo ‘ff02::02.       ip6-allrouters’ >> /etc/hosts
echo ‘’ >> /etc/hosts
echo "127.0.1.1.                 $HNAME" >> /etc/hosts

# Set Static IP,Router,DNS // Disable ipv6

# sudo vi /etc/resolv.conf

echo "# Generated by piHunter" > /etc/resolv.conf
echo "domain home" >> /etc/resolve.conf
echo "nameserver $HDNS" >> /etc/resolv.conf

# set static IPs
# add loop for multiple interfaces
echo "interface $INTERFACE" >> /etc/dhcpcd.conf
echo "static ip_address=$HIP/24" >> /etc/dhcpcd.conf
echo "static routers=$ROUTERIP" >> /etc/dhcpcd.conf
echo "static domain_name_servers=$HDNS" >> /etc/dhcpcd.conf

echo "auto $INTERFACE" >> /etc/network/interfaces
echo "iface $INTERFACE inet manual" >> /etc/network/interfaces
echo " address $HIP/24" >> /etc/network/interfaces
echo " gateway $ROUTERIP" >> /etc/network/interfaces

# edit network/interfaces file
echo "" >> /etc/network/interfaces
echo "auto $INTERFACE" >> /etc/network/interfaces
echo "iface $INTERFACE inet manual" >> /etc/network/interfaces
echo " address $HIP/24" >> /etc/network/interfaces
echo " gateway $ROUTERIP" >> /etc/network/interfaces

# external storage setup

# make dir for mount point
mkdir /hunt-xs

###################################
# Download and extract PowerShell

# Grab the latest tar.gz
wget https://github.com/PowerShell/PowerShell/releases/download/v7.1.3/powershell-7.1.3-linux-arm64.tar.gz

# Make folder to put powershell
mkdir /usr/bin/powershell

# Unpack the tar.gz file
tar -xzvf ./powershell-7.1.3-linux-arm64.tar.gz -C /usr/bin/powershell

# remove pwsh install file
rm -rf powershell-7.1.3-linux-arm64.tar.gz

# script - stop
